In [1]:
import pandas as pd

df = pd.read_csv('Online_Courses.csv')
df

,Unnamed: 0,Title,URL,Short Intro,Category,Sub-Category,Course Type,Language,Subtitle Languages,Skills,...,Course Short Intro,Weekly study,Premium course,What's include,Rank,Created by,Program,Number of ratings,Price,COURSE CATEGORIES
0,0,Machine Learning Specialization,https://www.coursera.org/specializations/machi...,#BreakIntoAI with Machine Learning Specializat...,Data Science,Machine Learning,Specialization,English,Subtitles: English,"Decision Trees, Artificial Neural Network, Log...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Introduction to Data Science Specialization,https://www.coursera.org/specializations/intro...,Launch your career in data science. Gain found...,Data Science,Data Analysis,Specialization,English,"Subtitles: English, Arabic, French, Portuguese...","Data Science, Relational Database Management S...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Data Science Fundamentals with Python and SQL ...,https://www.coursera.org/specializations/data-...,Build the Foundation for your Data Science car...,Data Science,Data Analysis,Specialization,English,"Subtitles: English, Arabic, French, Portuguese...","Data Science, Github, Python Programming, Jupy...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Key Technologies for Business Specialization,https://www.coursera.org/specializations/key-t...,Get Ahead with Key Business Technologies. Gain...,Business,Business Essentials,Specialization,English,"Subtitles: English, Arabic, French, Portuguese...","Data Science, Artificial Intelligence (AI), Bu...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Deep Learning Specialization,https://www.coursera.org/specializations/deep-...,Become a Machine Learning expert. Master the f...,Data Science,Machine Learning,Specialization,English,"Subtitles: English, Chinese (Traditional), Ara...","Artificial Neural Network, Convolutional Neura...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8087,143,Certified Scrum Master,https://www.simplilearn.com/certified-scrum-ma...,This Certified ScrumMasterÂ® (CSM) certificatio...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Course,369,NaN,Agile and Scrum
8088,144,Salesforce Basics Course for Beginners,https://www.simplilearn.com/salesforce-course?...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Course,348,NaN,Big Data
8089,145,ICP-ACC (ICAgile Certified Agile Coaching) Cer...,https://www.simplilearn.com/certified-agile-co...,This ICP-ACC Certification Training Course aim...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Course,301,NaN,Agile and Scrum
8090,146,/irisprodflip456,https://www.simplilearn.com/irisprodflip456?tag=,Iris Production check 456,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Course,293,NaN,Big Data Analytics
8091,147,Introduction to Industry 4.0,https://www.simplilearn.com/introduction-indus...,Introduction to Industry 4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Course,240,NaN,Business and Leadership

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8092 entries, 0 to 8091
Data columns (total 45 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             8092 non-null   int64
 1   Title                  8092 non-null   object
 2   URL                    8092 non-null   object
 3   Short Intro            8040 non-null   object
 4   Category               2819 non-null   object
 5   Sub-Category           2819 non-null   object
 6   Course Type            2819 non-null   object
 7   Language               2819 non-null   object
 8   Subtitle Languages     2802 non-null   object
 9   Skills                 2099 non-null   object
 10  Instructors            2808 non-null   object
 11  Rating                 2742 non-null   object
 12  Number of viewers      2695 non-null   object
 13  Duration               7944 non-null   object
 14  Site                   8092 non-null   object
 15  Program Type           282 non-null    object
 16  Courses                4944 non-null   object
 17  Level                  181 non-null    object
 18  Number of Reviews      47 non-null     object
 19  Unique Projects        0 non-null      float64
 20  Prequisites            281 non-null    object
 21  What you learn         278 non-null    object
 22  Related Programs       85 non-null     object
 23  Monthly access         98 non-null     object
 24  6-Month access         2 non-null      object
 25  4-Month access         38 non-null     object
 26  3-Month access         26 non-null     object
 27  5-Month access         2 non-null      object
 28  2-Month access         10 non-null     object
 29  School                 271 non-null    object
 30  Topics related to CRM  4666 non-null   object
 31  ExpertTracks           4843 non-null   object
 32  FAQs                   1083 non-null   object
 33  Course Title           4843 non-null   object
 34  Course URL             4843 non-null   object
 35  Course Short Intro     4843 non-null   object
 36  Weekly study           4843 non-null   object
 37  Premium course         1622 non-null   object
 38  What's include         419 non-null    object
 39  Rank                   37 non-null     object
 40  Created by             37 non-null     object
 41  Program                148 non-null    object
 42  Number of ratings      126 non-null    object
 43  Price                  65 non-null     float64
 44  COURSE CATEGORIES      148 non-null    object
dtypes: float64(2), int64(1), object(42)
memory usage: 2.8+ MB

In [5]:
df.describe()

       Unnamed: 0  Unique Projects        Price
count  8092.00000              0.0    65.000000
mean   1946.04214              NaN   903.830769
std    1346.92197              NaN   665.949617
min       0.00000              NaN   129.000000
25%     796.00000              NaN   534.000000
50%    1807.50000              NaN   855.000000
75%    2819.25000              NaN  1099.000000
max    4842.00000              NaN  4600.000000